version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./static
        target: /app/static